name: PHP Syntax Check
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check PHP Syntax
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l
